sudo: required
services:
  - docker

before_install:
  - docker build -t sulav/docker-react -f Dockerfile.dev  .

script:
  - docker run sulav/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-301231231241241"
  bucket_path: "docker-react"
  on:
    branch: master # Deploy when Changes are on Master Branch
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "AWS_SECRET_KEY"
